// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/// @title  MerkleCompat
/// @notice The highest-risk cross-language test in Phase 2: proves
///         backend/blockchain/merkle.py's tree construction (leaf
///         double-hashing, sorted-pair hashing, odd-node promotion)
///         produces proofs that verify against the REAL on-chain
///         OpenZeppelin MerkleProof.verify() — not a Python-side
///         reimplementation of the same algorithm, which could share a
///         bug with the thing it's supposed to be checking.
///
///         Fixtures are generated by backend/scripts/gen_merkle_fixtures.py
///         and must be regenerated (`python3 scripts/gen_merkle_fixtures.py`
///         from backend/) whenever merkle.py's algorithm changes — this
///         test only proves the *committed* fixture file verifies, it
///         can't detect a Python-side algorithm change that wasn't
///         re-exported.
contract MerkleCompatTest is Test {
    string constant FIXTURE_PATH = "test/fixtures/merkle_vectors.json";
    string json;

    function setUp() public {
        json = vm.readFile(FIXTURE_PATH);
    }

    function _leaves(uint256 n) internal view returns (bytes32[] memory) {
        return vm.parseJsonBytes32Array(json, string.concat(".n", vm.toString(n), "_leaves"));
    }

    function _root(uint256 n) internal view returns (bytes32) {
        return vm.parseJsonBytes32(json, string.concat(".n", vm.toString(n), "_root"));
    }

    function _proof(uint256 n, uint256 i) internal view returns (bytes32[] memory) {
        return vm.parseJsonBytes32Array(json, string.concat(".n", vm.toString(n), "_proof", vm.toString(i)));
    }

    /// @dev Every leaf in every fixture tree must verify against its own
    ///      tree's root using its own proof — the actual on-chain verifier,
    ///      not a reimplementation.
    function _assertAllLeavesVerify(uint256 n) internal view {
        bytes32[] memory leaves = _leaves(n);
        bytes32 root = _root(n);
        assertEq(leaves.length, n, "fixture leaf count mismatch");

        for (uint256 i = 0; i < n; i++) {
            bytes32[] memory proof = _proof(n, i);
            bool ok = MerkleProof.verify(proof, root, leaves[i]);
            assertTrue(ok, string.concat("leaf ", vm.toString(i), " of n=", vm.toString(n), " failed to verify"));
        }
    }

    function test_Verify_N1() public view {
        _assertAllLeavesVerify(1);
    }

    function test_Verify_N2() public view {
        _assertAllLeavesVerify(2);
    }

    function test_Verify_N3() public view {
        _assertAllLeavesVerify(3);
    }

    function test_Verify_N5() public view {
        _assertAllLeavesVerify(5);
    }

    function test_Verify_N8() public view {
        _assertAllLeavesVerify(8);
    }

    function test_Verify_N13() public view {
        _assertAllLeavesVerify(13);
    }

    /// @dev Negative case — a tampered proof must NOT verify. Without this,
    ///      a verifier that always returns true would pass every test above.
    function test_RevertOnTamperedProof() public view {
        bytes32[] memory leaves = _leaves(5);
        bytes32 root = _root(5);
        bytes32[] memory proof = _proof(5, 2);

        // Flip one bit in the first proof element.
        proof[0] = proof[0] ^ bytes32(uint256(1));

        assertFalse(MerkleProof.verify(proof, root, leaves[2]));
    }

    /// @dev A leaf from one tree must not verify against a different tree's
    ///      root, even with a structurally valid-looking proof from the
    ///      first tree.
    function test_RevertOnWrongRoot() public view {
        bytes32[] memory leaves5 = _leaves(5);
        bytes32[] memory proof5_0 = _proof(5, 0);
        bytes32 root8 = _root(8);

        assertFalse(MerkleProof.verify(proof5_0, root8, leaves5[0]));
    }

    /// @dev Single-leaf tree: root == leaf, empty proof. Not a special case
    ///      in the verifier (zero proof-fold iterations), but worth an
    ///      explicit assertion since it's the smallest/edge input.
    function test_SingleLeafTreeRootEqualsLeaf() public view {
        bytes32[] memory leaves = _leaves(1);
        bytes32 root = _root(1);
        assertEq(root, leaves[0]);

        bytes32[] memory proof = _proof(1, 0);
        assertEq(proof.length, 0);
        assertTrue(MerkleProof.verify(proof, root, leaves[0]));
    }
}
