"""steps, outbox, anchor batches, read model scores, indexer cursor

Revision ID: 2d9a96d1f2ab
Revises: 7891e5c31e5e
Create Date: 2026-08-13 23:53:10.441000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9a96d1f2ab'
down_revision: Union[str, Sequence[str], None] = '7891e5c31e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id_hash', sa.String(length=66), nullable=False),
    sa.Column('merkle_root', sa.String(length=66), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('leaf_order', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('onchain_anchor_id', sa.BigInteger(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anchor_batches_merkle_root'), 'anchor_batches', ['merkle_root'], unique=False)
    op.create_index(op.f('ix_anchor_batches_run_id_hash'), 'anchor_batches', ['run_id_hash'], unique=False)
    op.create_index(op.f('ix_anchor_batches_status'), 'anchor_batches', ['status'], unique=False)
    op.create_index(op.f('ix_anchor_batches_tx_hash'), 'anchor_batches', ['tx_hash'], unique=False)
    op.create_table('indexer_cursor',
    sa.Column('contract_name', sa.String(length=64), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('last_block_hash', sa.String(length=66), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('contract_name')
    )
    op.create_table('rm_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'log_index', name='uq_rm_scores_tx_hash_log_index')
    )
    op.create_index(op.f('ix_rm_scores_agent_id'), 'rm_scores', ['agent_id'], unique=False)
    op.create_index(op.f('ix_rm_scores_run_id'), 'rm_scores', ['run_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=66), nullable=False),
    sa.Column('output_hash', sa.String(length=66), nullable=False),
    sa.Column('leaf_hash', sa.String(length=66), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('anchor_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_batch_id'], ['anchor_batches.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leaf_hash')
    )
    op.create_index(op.f('ix_steps_anchor_batch_id'), 'steps', ['anchor_batch_id'], unique=False)
    op.create_index(op.f('ix_steps_run_id'), 'steps', ['run_id'], unique=False)
    op.create_table('anchor_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.BigInteger(), nullable=True),
    sa.Column('next_attempt_at', sa.BigInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['anchor_batches.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id')
    )
    op.create_index(op.f('ix_anchor_outbox_next_attempt_at'), 'anchor_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_anchor_outbox_status'), 'anchor_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anchor_outbox_status'), table_name='anchor_outbox')
    op.drop_index(op.f('ix_anchor_outbox_next_attempt_at'), table_name='anchor_outbox')
    op.drop_table('anchor_outbox')
    op.drop_index(op.f('ix_steps_run_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_anchor_batch_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_rm_scores_run_id'), table_name='rm_scores')
    op.drop_index(op.f('ix_rm_scores_agent_id'), table_name='rm_scores')
    op.drop_table('rm_scores')
    op.drop_table('indexer_cursor')
    op.drop_index(op.f('ix_anchor_batches_tx_hash'), table_name='anchor_batches')
    op.drop_index(op.f('ix_anchor_batches_status'), table_name='anchor_batches')
    op.drop_index(op.f('ix_anchor_batches_run_id_hash'), table_name='anchor_batches')
    op.drop_index(op.f('ix_anchor_batches_merkle_root'), table_name='anchor_batches')
    op.drop_table('anchor_batches')
    # ### end Alembic commands ###
