"""gas spend attribution on anchor batches

Revision ID: 695a83103ad6
Revises: b43560179de4
Create Date: 2026-08-15 13:17:27.598897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695a83103ad6'
down_revision: Union[str, Sequence[str], None] = 'b43560179de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anchor_batches', sa.Column('gas_used', sa.BigInteger(), nullable=True))
    op.add_column('anchor_batches', sa.Column('gas_price_wei', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anchor_batches', 'gas_price_wei')
    op.drop_column('anchor_batches', 'gas_used')
    # ### end Alembic commands ###
