"""project id namespacing for agent identity read model

Revision ID: 7c76a6e1b5ee
Revises: 695a83103ad6
Create Date: 2026-08-15 14:50:51.671059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c76a6e1b5ee'
down_revision: Union[str, Sequence[str], None] = '695a83103ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # rm_agent_events is a pure read model (invariant I6 — see
    # ReadModelAgentEvent's docstring), genuinely rebuildable from chain
    # events, not source-of-truth data — so adding a NOT NULL column here
    # doesn't need a backfill pass computing project_id for historical
    # rows (those events, emitted by the OLD non-namespaced contract,
    # never had a projectId to begin with). Instead: truncate the table
    # and rewind the 3 AgentIdentityRegistryV2 event streams' cursors to
    # genesis, so the indexer's own next poll cycle replays every event
    # and repopulates it for real — the same "wipe + replay" recovery
    # path already proven for real in
    # tests/test_indexer.py::test_indexer_rebuilds_read_model_identically_from_genesis.
    op.execute("TRUNCATE TABLE rm_agent_events")
    op.execute(
        "DELETE FROM indexer_cursor WHERE contract_name IN ("
        "'AgentIdentityRegistryV2:AgentRegistered', "
        "'AgentIdentityRegistryV2:AgentRevoked', "
        "'AgentIdentityRegistryV2:IntegrityViolation')"
    )
    op.add_column('rm_agent_events', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_rm_agent_events_project_id'), 'rm_agent_events', ['project_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rm_agent_events_project_id'), table_name='rm_agent_events')
    op.drop_column('rm_agent_events', 'project_id')
    # ### end Alembic commands ###
