"""agent identity read model events

Revision ID: b43560179de4
Revises: 9f3a1c7d5e2b
Create Date: 2026-08-15 10:53:01.567524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43560179de4'
down_revision: Union[str, Sequence[str], None] = '9f3a1c7d5e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rm_agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=42), nullable=True),
    sa.Column('code_hash', sa.String(length=66), nullable=True),
    sa.Column('expected_hash', sa.String(length=66), nullable=True),
    sa.Column('provided_hash', sa.String(length=66), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'log_index', name='uq_rm_agent_events_tx_hash_log_index')
    )
    op.create_index(op.f('ix_rm_agent_events_agent_id'), 'rm_agent_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_rm_agent_events_event_type'), 'rm_agent_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rm_agent_events_event_type'), table_name='rm_agent_events')
    op.drop_index(op.f('ix_rm_agent_events_agent_id'), table_name='rm_agent_events')
    op.drop_table('rm_agent_events')
    # ### end Alembic commands ###
