"""
blockchain/merkle.py — Merkle tree construction matching AgentAuditLogV2's
on-chain verifier (OpenZeppelin's MerkleProof.sol) exactly.

This is the single highest cross-language-compatibility risk in Phase 2:
if leaf encoding, pair-hashing, or odd-node handling here diverges from
what MerkleProof.verify() expects on-chain, proofs silently fail to verify
— see contracts/test/MerkleCompat.t.sol, which cross-checks fixtures
generated by this module against the real on-chain verifier, not just
Python-side unit tests.

ALGORITHM
─────────
1. Leaves are double-hashed: leaf = keccak256(keccak256(preimage)).
   A single hash is NOT enough — see `leaf_hash`'s docstring for the
   concrete forgery it would allow.

2. Pairs are hashed in sorted order: hash_pair(a, b) always hashes
   min(a,b) || max(a,b), regardless of which one is the "left" or "right"
   child. This is what lets a verifier walk a proof without needing to
   know tree structure/direction — OpenZeppelin's `_hashPair` does the
   same sort.

3. An odd node at any level is promoted UNCHANGED to the next level, never
   duplicated. Duplicating the last node (pairing it with itself) is the
   well-known CVE-2012-2459-class bug — it lets an attacker prove a
   4-leaf tree's root from only 3 real leaves by exploiting the
   duplicate. Promoting instead means that node simply has no sibling at
   that level (the proof omits an entry for it there).
"""

from __future__ import annotations

from dataclasses import dataclass

from eth_abi import encode as abi_encode
from web3 import Web3


def _keccak(data: bytes) -> bytes:
    return bytes(Web3.keccak(data))


def leaf_hash(
    run_id_hash: bytes,
    agent_id_hash: bytes,
    action_hash: bytes,
    input_hash: bytes,
    output_hash: bytes,
    step_index: int,
    timestamp: int,
) -> bytes:
    """
    Double-hashed leaf for one anchored step.

    Only fixed-width fields (bytes32/uint64) go into the preimage — no
    dynamic types (strings, byte arrays). Dynamic ABI encoding adds length
    prefixes and offset words whose exact byte layout is easy to get
    subtly wrong reproducing across languages; hashing variable-length
    content first (see hashing_utils.compute_hash) and only packing fixed
    32/8-byte fields here sidesteps that entirely.

    Double-hashing matters beyond "defense in depth": with a *single*
    hash, an attacker could pick preimage bytes equal to the 64-byte
    concatenation of some real internal node's two children — since
    abi.encode(bytes32,bytes32) IS that concatenation, keccak256(preimage)
    would reproduce that internal node's hash for free, no cryptographic
    work required. The attacker could then reuse that node's real sibling
    path as a "proof" for data that was never actually one of the tree's
    leaves. Double-hashing means forging a leaf requires an actual keccak
    preimage attack, not a structural coincidence.
    """
    preimage = abi_encode(
        ["bytes32", "bytes32", "bytes32", "bytes32", "bytes32", "uint64", "uint64"],
        [run_id_hash, agent_id_hash, action_hash, input_hash, output_hash, step_index, timestamp],
    )
    return _keccak(_keccak(preimage))


def leaf_hash_v2(
    run_id_hash: bytes,
    agent_id_hash: bytes,
    action_hash: bytes,
    input_hash: bytes,
    output_hash: bytes,
    step_index: int,
    timestamp: int,
    agent_code_hash: bytes,
) -> bytes:
    """
    Identity-bound leaf (Phase 3 §6.2) — leaf_hash's exact preimage plus
    one more bytes32: the SDK's own fingerprint of the agent that
    produced this step. WHY THIS MATTERS: storing agent_code_hash as an
    ordinary `steps` column would be database-editable by the same
    attacker this whole system exists to catch — putting it in the leaf
    preimage means editing that column breaks the anchored hash, exactly
    like editing input_hash/output_hash already does. An attacker with DB
    access can no longer make a step LOOK like it was produced by a
    different, unregistered identity without also invalidating the
    Merkle proof that step's batch anchored on-chain.

    THIS IS A NEW SCHEME, NOT A REPLACEMENT: `steps.leaf_schema_version`
    (default 1) tracks which preimage a given row's leaf_hash was built
    from — leaf_hash (v1) for every row anchored before Phase 3, this
    function (v2) for rows an identity-aware SDK logs afterward. A v1 and
    a v2 leaf coexist in the SAME Merkle tree with no special handling —
    build_tree/build_levels operate on opaque 32-byte leaves regardless of
    which preimage produced them, and AgentAuditLogV2.verifyProof takes an
    opaque bytes32 leaf too; the contract never knew either preimage.
    Existing anchored proofs are completely unaffected.
    """
    preimage = abi_encode(
        ["bytes32", "bytes32", "bytes32", "bytes32", "bytes32", "uint64", "uint64", "bytes32"],
        [run_id_hash, agent_id_hash, action_hash, input_hash, output_hash, step_index, timestamp, agent_code_hash],
    )
    return _keccak(_keccak(preimage))


def hash_pair(a: bytes, b: bytes) -> bytes:
    """Sorted-pair hash — matches OpenZeppelin MerkleProof.sol's _hashPair
    exactly. Order of arguments never matters, only numeric value (Python
    bytes comparison is lexicographic/big-endian, same as a uint256
    comparison of the same bytes)."""
    return _keccak(a + b) if a < b else _keccak(b + a)


def build_levels(leaves: list[bytes]) -> list[list[bytes]]:
    """
    Builds every level of the tree, leaves first, root last (a
    single-element list). Odd nodes at any level are promoted unchanged —
    see module docstring for why that matters.
    """
    if not leaves:
        raise ValueError("cannot build a Merkle tree from an empty leaf list")

    levels = [list(leaves)]
    current = levels[0]
    while len(current) > 1:
        next_level: list[bytes] = []
        i = 0
        while i < len(current):
            if i + 1 < len(current):
                next_level.append(hash_pair(current[i], current[i + 1]))
                i += 2
            else:
                next_level.append(current[i])  # unpaired — promoted, not duplicated
                i += 1
        levels.append(next_level)
        current = next_level
    return levels


def proof_for(levels: list[list[bytes]], index: int) -> list[bytes]:
    """Sibling hashes needed to walk `levels[0][index]` up to the root.
    Skips a level entirely when the node had no sibling there (it was the
    odd one out, promoted unchanged) — matching how build_levels built it."""
    if index < 0 or index >= len(levels[0]):
        raise IndexError(f"leaf index {index} out of range for {len(levels[0])} leaves")

    proof: list[bytes] = []
    idx = index
    for level in levels[:-1]:
        sibling_idx = idx - 1 if idx % 2 else idx + 1
        if sibling_idx < len(level):
            proof.append(level[sibling_idx])
        idx //= 2
    return proof


def verify_proof(leaf: bytes, proof: list[bytes], root: bytes) -> bool:
    """Pure-Python mirror of MerkleProof.verify — walk the proof from the
    leaf, folding in each sibling, and check the result matches the root.
    Used to self-check a generated proof before ever submitting a root
    on-chain; the authoritative check still happens in
    AgentAuditLogV2.verifyProof (a real EVM call), not here."""
    computed = leaf
    for sibling in proof:
        computed = hash_pair(computed, sibling)
    return computed == root


@dataclass(frozen=True)
class MerkleTree:
    leaves: list[bytes]
    levels: list[list[bytes]]

    @property
    def root(self) -> bytes:
        return self.levels[-1][0]

    def proof(self, index: int) -> list[bytes]:
        return proof_for(self.levels, index)

    def proof_hex(self, index: int) -> list[str]:
        return ["0x" + p.hex() for p in self.proof(index)]

    @property
    def root_hex(self) -> str:
        return "0x" + self.root.hex()


def build_tree(leaves: list[bytes]) -> MerkleTree:
    return MerkleTree(leaves=list(leaves), levels=build_levels(leaves))
